type Product @model {
  id: ID
  supplier: String
  url: String
  product_line: String
  article: String
  images: [String]
  power: String
  lumen: String
  color_temp: String
  size: String
  control_system: String
  optic_type_code: String
  mounting: String
}
